<?php

namespace app\modules\api;

use yii\base\Module as BaseModule;
use Yii;

class Module extends BaseModule
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (Yii::$app instanceof \yii\web\Application) {
            $this->controllerNamespace = 'app\modules\api\controllers';
        }
    }
}